import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const projectRoot = process.cwd();
const outputDir = path.join(projectRoot, "mobile-web");

const rootEntriesToCopy = [
  "index.html",
  "fiber-color-code.html",
  "twisted-pair-color-code.html",
  "ethernet-reference.html",
  "coax-reference.html",
  "privacy.html",
  "terms.html",
  "style.css",
  "script.js",
  "service-worker.js",
  "manifest.json",
  "robots.txt",
  "sitemap.xml"
];

function resetOutputDirectory() {
  mkdirSync(outputDir, { recursive: true });

  const generatedEntries = [
    ...rootEntriesToCopy,
    "README.txt"
  ];

  generatedEntries.forEach(entryName => {
    const entryPath = path.join(outputDir, entryName);

    if (!existsSync(entryPath)) {
      return;
    }

    rmSync(entryPath, { recursive: true, force: true });
  });
}

function copyEntry(entryName) {
  const sourcePath = path.join(projectRoot, entryName);

  if (!existsSync(sourcePath)) {
    return;
  }

  const destinationPath = path.join(outputDir, entryName);
  const sourceStats = statSync(sourcePath);

  if (sourceStats.isDirectory()) {
    cpSync(sourcePath, destinationPath, { recursive: true, force: true });
    return;
  }

  cpSync(sourcePath, destinationPath, { force: true });
}

function copyTopLevelMedia() {
  const topLevelEntries = readdirSync(projectRoot);

  topLevelEntries.forEach(entryName => {
    const extension = path.extname(entryName).toLowerCase();
    const isMediaAsset = [".png", ".jpg", ".jpeg", ".webp", ".svg", ".ico"].includes(extension);

    if (!isMediaAsset) {
      return;
    }

    copyEntry(entryName);
  });
}

function writeMobileReadme() {
  const readmePath = path.join(outputDir, "README.txt");
  const readmeContent = [
    "This folder is generated by `npm run mobile:prepare`.",
    "Capacitor uses it as the packaged web bundle for Android and iPhone builds.",
    "Do not hand-edit files here because the next prepare step will overwrite them."
  ].join("\n");

  writeFileSync(readmePath, `${readmeContent}\n`);
}

resetOutputDirectory();
rootEntriesToCopy.forEach(copyEntry);
copyTopLevelMedia();
writeMobileReadme();

console.log("Prepared mobile-web bundle for Capacitor.");
